name: Build Images
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+
  workflow_dispatch:
jobs:
  init-variable:
    runs-on: ubuntu-24.04
    outputs:
      container_tag: ${{ steps.init_variable.outputs.container_tag }}
      platforms: ${{ steps.init_variable.outputs.platforms }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: output environment variable
        id: init_variable
        run: |
          set -x
          if [[ $GITHUB_REF =~ ^refs/tags/v ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            PLATFORMS="linux/amd64,linux/arm64"
          else
            VERSION=$(git describe --tags --abbrev=8)
            PLATFORMS="linux/amd64"
          fi
          echo "container_tag=${VERSION}" >> $GITHUB_OUTPUT
          echo "platforms=${PLATFORMS}" >> $GITHUB_OUTPUT
  build-mail-approve:
    permissions:
      contents: read
      packages: write
    needs: [ init-variable ]
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: use-setup-buildx-action
        uses: docker/setup-buildx-action@v3
      - name: login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build jenkins
        uses: docker/build-push-action@v6
        with:
          context: ./custom-steps/mail-approve/
          file: ./custom-steps/mail-approve/Dockerfile
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push: true
          provenance: false
          platforms: ${{ needs.init-variable.outputs.platforms }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/custom-step-mail-approve:${{ needs.init-variable.outputs.container_tag }}
            ${{ secrets.DOCKER_USERNAME }}/custom-step-mail-approve:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max